ignore:
  - '**/*.module.*'
  - '**/*.entity.*'
  - '**/*.dto.*'
  - '**/*.enum.*'
  - '**/*.generated.*'
  - '**/*initializer.*'
  - '**/*main.*'
  - '**/config.mts'
  - '**/index.ts'
  - '**/datasource/*.js'
  - '**/migrations/*.ts'
